%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosEventDomainAdmin_ConnectionNotFound
%% Source: /build/erlang-khbCpQ/erlang-20.2.2+dfsg/lib/cosEventDomain/src/CosEventDomainAdmin.idl
%% IC vsn: 4.4.3
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosEventDomainAdmin_ConnectionNotFound').
-ic_compiled("4_4_3").


-include("CosEventDomainAdmin.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosEventDomainAdmin/ConnectionNotFound:1.0",
                   "ConnectionNotFound",[]}.

%% returns id
id() -> "IDL:omg.org/CosEventDomainAdmin/ConnectionNotFound:1.0".

%% returns name
name() -> "CosEventDomainAdmin_ConnectionNotFound".



