%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosNotifyComm
%% Source: /build/erlang-khbCpQ/erlang-20.2.2+dfsg/lib/cosNotification/src/CosNotifyComm.idl
%% IC vsn: 4.4.3
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSNOTIFYCOMM_HRL).
-define(COSNOTIFYCOMM_HRL, true).


-record('CosNotifyComm_InvalidEventType', {'OE_ID'="IDL:omg.org/CosNotifyComm/InvalidEventType:1.0", type}).


-endif.


