%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosTime_TIO
%% Source: /build/erlang-khbCpQ/erlang-20.2.2+dfsg/lib/cosTime/src/CosTime.idl
%% IC vsn: 4.4.3
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSTIME_TIO_HRL).
-define(COSTIME_TIO_HRL, true).




-endif.


