%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosEventChannelAdmin_ProxyPullConsumer
%% Source: /build/erlang-khbCpQ/erlang-20.2.2+dfsg/lib/cosEvent/src/CosEventChannelAdmin.idl
%% IC vsn: 4.4.3
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSEVENTCHANNELADMIN_PROXYPULLCONSUMER_HRL).
-define(COSEVENTCHANNELADMIN_PROXYPULLCONSUMER_HRL, true).




-endif.


