%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_CosEventComm
%% Source: /build/erlang-khbCpQ/erlang-20.2.2+dfsg/lib/cosEvent/src/CosEventComm.idl
%% IC vsn: 4.4.3
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_COSEVENTCOMM_HRL).
-define(OE_COSEVENTCOMM_HRL, true).




-endif.


