%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: erlang
%% Source: /build/erlang-khbCpQ/erlang-20.2.2+dfsg/lib/ic/include/erlang.idl
%% IC vsn: 4.4.3
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(ERLANG_HRL).
-define(ERLANG_HRL, true).


-record(erlang_pid, {node, num, serial, creation}).
-record(erlang_port, {node, id, creation}).
-record(erlang_ref, {node, id, creation}).


-endif.


