%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_erlang
%% Source: /build/erlang-khbCpQ/erlang-20.2.2+dfsg/lib/ic/include/erlang.idl
%% IC vsn: 4.4.3
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_ERLANG_HRL).
-define(OE_ERLANG_HRL, true).




-endif.


