%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosPropertyService_PropertySetFactory
%% Source: /build/erlang-khbCpQ/erlang-20.2.2+dfsg/lib/cosProperty/src/CosProperty.idl
%% IC vsn: 4.4.3
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSPROPERTYSERVICE_PROPERTYSETFACTORY_HRL).
-define(COSPROPERTYSERVICE_PROPERTYSETFACTORY_HRL, true).




-endif.


