%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_CosProperty
%% Source: /build/erlang-khbCpQ/erlang-20.2.2+dfsg/lib/cosProperty/src/CosProperty.idl
%% IC vsn: 4.4.3
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_COSPROPERTY_HRL).
-define(OE_COSPROPERTY_HRL, true).




-endif.


