%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_OrberIFR
%% Source: /build/erlang-khbCpQ/erlang-20.2.2+dfsg/lib/orber/src/OrberIFR.idl
%% IC vsn: 4.4.3
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_ORBERIFR_HRL).
-define(OE_ORBERIFR_HRL, true).




-endif.


