%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosFileTransfer_FileTransferSession
%% Source: /build/erlang-khbCpQ/erlang-20.2.2+dfsg/lib/cosFileTransfer/src/CosFileTransfer.idl
%% IC vsn: 4.4.3
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSFILETRANSFER_FILETRANSFERSESSION_HRL).
-define(COSFILETRANSFER_FILETRANSFERSESSION_HRL, true).




-endif.


