%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: ETraP
%% Source: /build/erlang-khbCpQ/erlang-20.2.2+dfsg/lib/cosTransactions/src/CosTransactions.idl
%% IC vsn: 4.4.3
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(ETRAP_HRL).
-define(ETRAP_HRL, true).




-endif.


