%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosNotifyChannelAdmin_StructuredProxyPullConsumer
%% Source: /build/erlang-khbCpQ/erlang-20.2.2+dfsg/lib/cosNotification/src/CosNotifyChannelAdmin.idl
%% IC vsn: 4.4.3
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSNOTIFYCHANNELADMIN_STRUCTUREDPROXYPULLCONSUMER_HRL).
-define(COSNOTIFYCHANNELADMIN_STRUCTUREDPROXYPULLCONSUMER_HRL, true).




-endif.


