%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosTransactions_HeuristicMixed
%% Source: /build/erlang-khbCpQ/erlang-20.2.2+dfsg/lib/cosTransactions/src/CosTransactions.idl
%% IC vsn: 4.4.3
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosTransactions_HeuristicMixed').
-ic_compiled("4_4_3").


-include("CosTransactions.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosTransactions/HeuristicMixed:1.0",
                   "HeuristicMixed",[]}.

%% returns id
id() -> "IDL:omg.org/CosTransactions/HeuristicMixed:1.0".

%% returns name
name() -> "CosTransactions_HeuristicMixed".



