%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_CosFileTransfer
%% Source: /build/erlang-khbCpQ/erlang-20.2.2+dfsg/lib/cosFileTransfer/src/CosFileTransfer.idl
%% IC vsn: 4.4.3
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_COSFILETRANSFER_HRL).
-define(OE_COSFILETRANSFER_HRL, true).




-endif.


