%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosNaming_BindingIterator
%% Source: /build/erlang-khbCpQ/erlang-20.2.2+dfsg/lib/orber/COSS/CosNaming/cos_naming.idl
%% IC vsn: 4.4.3
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSNAMING_BINDINGITERATOR_HRL).
-define(COSNAMING_BINDINGITERATOR_HRL, true).




-endif.


