%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosNaming_NamingContext_InvalidName
%% Source: /build/erlang-khbCpQ/erlang-20.2.2+dfsg/lib/orber/COSS/CosNaming/cos_naming.idl
%% IC vsn: 4.4.3
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosNaming_NamingContext_InvalidName').
-ic_compiled("4_4_3").


-include("CosNaming_NamingContext.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosNaming/NamingContext/InvalidName:1.0",
                   "InvalidName",[]}.

%% returns id
id() -> "IDL:omg.org/CosNaming/NamingContext/InvalidName:1.0".

%% returns name
name() -> "CosNaming_NamingContext_InvalidName".



